### ISSUE TITLE
仕様検討

### ISSUE THREAD

**Issue by marihachi** [marihachi/mfm-parser-pegjs#4]
## 概要
MFMとしての仕様を検討します。

現状のMFMパーサーは実装に依存しています。
書き直しで全ての挙動を再現することになり、その挙動に何らかの意図があるのかどうかが現状では不明です。
仕様を決定することでパーサーの挙動が最適化・簡素化されることを狙っています。

このほうが良いなどあれば、ご意見をください。
これに沿って実装を進めていきます。

## 構文の定義に登場する記号・識別子の意味について
`"` `"` で囲まれた文字列 : 普通の文字列を表します。
`(` `or` `)` : 選択を表しています。
`+` : 1回以上の繰り返しを表しています。
`?` : オプションを表しています。あってもなくても大丈夫な部分です。
上記以外 : 項目毎にそれぞれ説明しています。
また、一部PEGの用語が含まれています。

### title(1)
タイトル行。現在位置から行末までマッチする。
```
beginline "【" inlines "】" endline
```
beginline:
行頭にマッチ(消費しない)
inlines:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)
endline:
改行文字またはEOFにマッチ

### title(2)
タイトル行。現在位置から行末までマッチする。
```
beginline "[" inlines "]" endline
```
beginline:
行頭にマッチ(消費しない)
inlines:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)
endline:
改行文字またはEOFにマッチ

### quote
引用ブロック。現在位置から行末までマッチする。
複数行で連結して1つの引用ブロックを形成する。
例外として、head">"に続いて"<"が出てきた場合や、head"＞"に続いて"＜"が出てきた場合にはマッチしない。
```
beginline head content endline
```
beginline:
行頭にマッチ(消費しない)
head:
`">" or "＞"`
content:
改行文字を除く任意の文字にマッチ(複数)
1文字目がスペースなら、2文字目から取り込む
取り込まれた文字列をブロック構文orインライン構文(複数)として処理
endline:
改行文字またはEOFにマッチ

### search
検索ボックス。現在位置から行末までマッチする。
```
beginline query " " ("検索" or "search") endline
```
beginline:
行頭にマッチ(消費しない)
query:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をそのまま保持
endline:
改行文字またはEOFにマッチ

### blockCode
コードブロック。「```」で囲まれた複数の行をコードブロックとして扱う
```
beginline "```" endline
(line endline)+
"```" endline
```
beginline:
行頭にマッチ(消費しない)
line:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をそのまま保持
endline:
改行文字またはEOFにマッチ

### mathBlock
数式ブロック
```
"\[" content "\]"
```
content:
任意の文字にマッチ(複数)
マッチした文字列を数式として処理

### conter
中央寄せブロック
```
"<center>" content "</center>"
```
content:
任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)

### big
拡大して揺れる太文字
```
"***" inlines "***"
```
inlines:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)

### bold(1)
太文字
```
"**" inlines "**"
```
inlines:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)

### bold(2)
太文字
```
"__" inlines "__"
```
inlines:
アルファベット(大文字 小文字) 数字 スペース のいずれかの文字にマッチ (複数)
マッチした文字列をインライン構文として処理(複数)

### small
小さな文字
```
"<small>" inlines "</small>"
```
inlines:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)

### italic(1)
イタリック文字
```
"<i>" inlines "</i>"
```
inlines:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)

### italic(2)
```
"*" inlines "*"
```
inlines:
アルファベット(大文字 小文字) 数字 スペース のいずれかの文字にマッチ (複数)
マッチした文字列をインライン構文として処理(複数)

### italic(3)
```
"_" inlines "_"
```
inlines:
アルファベット(大文字 小文字) 数字 スペース のいずれかの文字にマッチ (複数)
マッチした文字列をインライン構文として処理(複数)

### strike
打ち消し線の付いた文字
```
"~~" inlines "~~"
```
inlines:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)

### motion(1)
動く文字
```
"<motion>" inlines "</motion>"
```
inlines:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)

### motion(2)
```
"(((" inlines ")))"
```
inlines:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)

### spin
```
"<spin" (" " attr)? ">" inlines "</spin>"
```
attr:
改行文字を除く任意の文字にマッチ(複数)
inlines:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)

### jump
跳ねる文字
```
"<jump>" inlines "</jump>"
```
inlines:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)

### flip
反転する
```
"<flip>" inlines "</flip>"
```
inlines:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をインライン構文として処理(複数)

### inlineCode
コード
```
"`" chars "`"
```
chars:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列をコードの内容として処理

### mathInline
数式
```
"\(" chars "\)"
```
chars:
改行文字を除く任意の文字にマッチ(複数)
マッチした文字列を数式の内容として処理

### hashtag
ハッシュタグ。
ネストされたかっこの開始と終了が対になっている場合のみハッシュタグの内容に含める処理を持つ。
```
"#" content
```
content:
基本的には以下の正規表現にマッチする文字を内容として取り込みます。
正規表現: `` [^\s!"#$%&'*+,\-./:;<=>?@\\^_`{|}~【】＜＞] ``
その中で、ネストされたかっこ`()[]「」`の開始と終了が対になっている場合、その部分は内容に含めます。
それ以外の場合は、改行文字を除くかっこ`()[]「」`に一致しない文字を内容に含めます。

### text
プレーンな文字。他のルールに一致しなかった場合にフォールバックしてマッチする。
```
chars
```
chars:
改行文字を除く任意の文字にマッチ(複数)

**Comment by marihachi** [comment]
### bold(2)は改行以外のすべての文字にマッチしても良いかどうか
現行のパーサーでは、アルファベット 数字 スペース にマッチする

**Comment by syuilo** [comment]
_ は顔文字とかでよく使われるから、すべての文字にマッチすると誤って発動してしまう

**Comment by syuilo** [comment]
引用に関して:
半角の > だけでなく全角の ＞ も使う人が多いからそれもマッチさせたい
ただ＞＜という顔文字もあるからそれはマッチしないようにしたい

**Comment by marihachi** [comment]
@syuilo 
> _ は顔文字とかでよく使われるから、すべての文字にマッチすると誤って発動してしまう

なるほど、現行の挙動に合わせてみるよ

> 引用に関して

＞＜にマッチしないようにできるか考えてみる
